# -*- coding: utf-8 -*-
"""CNN - Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXBFXdySAbfpPFqMxogsbYJXHTC0hA30
"""

# ==============================================================
# 🛰️ CNN-Based Aerial and Satellite Image Interpretation
# Dataset: EuroSAT (RGB) ~27K images
# Environment: Google Colab (No TensorFlow Addons)
# ==============================================================

!pip install -q tensorflow tensorflow-datasets scikit-learn seaborn matplotlib

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras import layers, models, regularizers
import numpy as np, matplotlib.pyplot as plt, seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import itertools, random, os, pandas as pd

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

# ---------------- CONFIG -----------------
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

IMG_SIZE = (64, 64)
BATCH_SIZE = 64
AUTOTUNE = tf.data.AUTOTUNE
EPOCHS = 12

# ---------------- DATASET -----------------
(ds_train, ds_val, ds_test), ds_info = tfds.load(
    "eurosat/rgb",
    split=["train[:80%]", "train[80%:90%]", "train[90%:]"],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)
class_names = ds_info.features['label'].names
print("Classes:", class_names)

# ---------------- PREPROCESSING -----------------
def preprocess(image, label):
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

def augment(image, label):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_brightness(image, 0.1)
    image = tf.image.random_contrast(image, 0.8, 1.2)
    # Simulate rotation manually with 90-degree rotations
    k = tf.random.uniform(shape=[], minval=0, maxval=4, dtype=tf.int32)
    image = tf.image.rot90(image, k)
    return image, label

train_ds = ds_train.map(preprocess, num_parallel_calls=AUTOTUNE)
val_ds   = ds_val.map(preprocess, num_parallel_calls=AUTOTUNE)
test_ds  = ds_test.map(preprocess, num_parallel_calls=AUTOTUNE)

train_ds = train_ds.map(augment, num_parallel_calls=AUTOTUNE)
train_ds = train_ds.shuffle(1024).batch(BATCH_SIZE).prefetch(AUTOTUNE)
val_ds   = val_ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)
test_ds  = test_ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)

# ---------------- MODEL -----------------
def build_model(input_shape=IMG_SIZE+(3,), num_classes=len(class_names)):
    model = models.Sequential([
        layers.Conv2D(32,3,padding='same',activation='relu',input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D(2),
        layers.Dropout(0.25),

        layers.Conv2D(64,3,padding='same',activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(2),
        layers.Dropout(0.3),

        layers.Conv2D(128,3,padding='same',activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(2),
        layers.Dropout(0.4),

        layers.Flatten(),
        layers.Dense(256,activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes,activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model = build_model()
history = model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS, verbose=1)

# ---------------- PERFORMANCE GRAPHS -----------------
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy Comparison')
plt.legend()
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss Comparison')
plt.legend()
plt.show()

# ---------------- EVALUATION -----------------
test_loss, test_acc = model.evaluate(test_ds)
print(f"✅ Test Accuracy: {test_acc*100:.2f}%")

# predictions
y_true, y_pred = [], []
for images, labels in test_ds:
    preds = model.predict(images, verbose=0)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=class_names))

# ---------------- CONFUSION MATRIX -----------------
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title("Confusion Matrix (Class Correlation)")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# ---------------- CORRELATION MATRIX -----------------
cm_df = pd.DataFrame(cm, index=class_names, columns=class_names)
corr_matrix = cm_df.corr()
plt.figure(figsize=(9,7))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)
plt.title("Correlation Matrix Between Class Predictions")
plt.show()

# ---------------- OUTPUT IMAGE VISUALIZATION -----------------
def show_predictions(dataset, n=12):
    plt.figure(figsize=(15,10))
    for i, (image, label) in enumerate(dataset.unbatch().take(n)):
        ax = plt.subplot(3, 4, i+1)
        img = image.numpy()
        pred = np.argmax(model.predict(img[np.newaxis,...]), axis=1)[0]
        color = "green" if pred == label.numpy() else "red"
        plt.imshow(img)
        plt.title(f"T:{class_names[label]} / P:{class_names[pred]}", color=color, fontsize=9)
        plt.axis("off")
    plt.tight_layout()
    plt.show()

show_predictions(test_ds, n=12)

# ---------------- COMPARATIVE ANALYSIS TABLE -----------------
train_acc = history.history['accuracy'][-1]
val_acc   = history.history['val_accuracy'][-1]
train_loss = history.history['loss'][-1]
val_loss   = history.history['val_loss'][-1]

compare_df = pd.DataFrame({
    "Metric": ["Accuracy", "Loss"],
    "Training": [train_acc, train_loss],
    "Validation": [val_acc, val_loss],
    "Difference": [train_acc-val_acc, train_loss-val_loss]
})
print("\n📊 Comparative Analysis Table:\n")
print(compare_df)